on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Build container image
      run: docker build --tag docker.pkg.github.com/hugomd/lnd-invoice/lnd-invoice:$(echo $GITHUB_SHA | head -c7) .

    - name: Docker login
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login -u hugomd -p $GITHUB_TOKEN docker.pkg.github.com
      
    - name: Push image to Docker Hub
      run: docker push docker.pkg.github.com/hugomd/lnd-invoice/lnd-invoice
